
import React, { useState, useEffect } from 'react';
import { X, Mail, Lock, User as UserIcon, KeyRound, ArrowRight, AlertCircle, Loader2 } from 'lucide-react';
import { User } from '../types';
import { StorageService } from '../services/storage';

interface AuthModalProps {
  isOpen: boolean;
  onClose: () => void;
  onLogin: (user: User) => void;
}

const AuthModal: React.FC<AuthModalProps> = ({ isOpen, onClose, onLogin }) => {
  const [isLoginMode, setIsLoginMode] = useState(true);
  const [step, setStep] = useState<'credentials' | 'verification'>('credentials');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  
  // Form States
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [verificationCode, setVerificationCode] = useState('');

  useEffect(() => {
    if (isOpen) resetForm();
  }, [isOpen]);

  if (!isOpen) return null;

  const handleCredentialsSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
        if (isLoginMode) {
            // --- LOGIN FLOW ---
            const result = await StorageService.loginUser(email, password);
            if (result.success && result.user) {
                onLogin(result.user);
                onClose();
            } else {
                setError(result.message || "Ошибка входа");
            }
        } else {
            // --- REGISTER FLOW (Part 1: Check duplicates locally/Pre-check) ---
            // Note: We do the actual check in the "Verification" step or simple submit
            // For better UX, let's check duplicate email first if possible, 
            // but since we want to keep it robust, we'll move to verification step immediately
            // or just register if we want to skip fake verification. 
            // Let's keep the verification step for Registration ONLY as a "Spam Check" UI.
            setStep('verification');
        }
    } catch (err) {
        setError("Произошла неизвестная ошибка");
    } finally {
        setIsLoading(false);
    }
  };

  const handleRegisterFinalize = async (e: React.FormEvent) => {
    e.preventDefault();
    if (verificationCode.length < 4) {
        setError('Код слишком короткий');
        return;
    }

    setIsLoading(true);
    setError('');

    const newUser: User = {
        numericId: '', // Will be generated by storage service
        name: name || (email.split('@')[0]),
        email: email,
        password: password,
        joinedDate: new Date().toLocaleDateString('ru-RU'),
        favorites: [], // Initialize favorites
        ratedRecipeIds: [],
        bio: 'Начинающий гурман',
        votedComments: {},
        role: 'user',
        isBanned: false,
        settings: {
            showEmail: false,
            showFavorites: true,
            newsletter: true,
            dietaryPreferences: []
        }
    };

    const regResult = await StorageService.registerUser(newUser);
    
    if (regResult.success && regResult.user) {
        onLogin(regResult.user);
        onClose();
    } else {
        setError(regResult.message || "Ошибка регистрации");
        // Если ошибка (например дубликат), может стоить вернуться назад
        if (regResult.message.includes('уже зарегистрирован')) {
             setTimeout(() => setStep('credentials'), 2000);
        }
    }
    setIsLoading(false);
  };

  const resetForm = () => {
    setStep('credentials');
    setName('');
    setEmail('');
    setPassword('');
    setVerificationCode('');
    setError('');
    setIsLoading(false);
  };

  const switchMode = () => {
    setIsLoginMode(!isLoginMode);
    setStep('credentials');
    setError('');
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-md mx-4 bg-white dark:bg-gray-900 rounded-2xl shadow-2xl overflow-hidden border border-white/10">
        <button 
            onClick={onClose}
            className="absolute top-4 right-4 text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 z-10"
        >
            <X className="w-6 h-6" />
        </button>

        <div className="p-6 sm:p-8">
            {step === 'credentials' ? (
              <>
                <h2 className="font-serif text-2xl sm:text-3xl font-bold text-center mb-2 text-gray-900 dark:text-white">
                    {isLoginMode ? 'Вход в аккаунт' : 'Регистрация'}
                </h2>
                <p className="text-center text-gray-500 dark:text-gray-400 mb-6 text-sm">
                  {isLoginMode ? 'Введите Email и пароль' : 'Заполните данные для создания профиля'}
                </p>

                {error && (
                    <div className="mb-4 p-3 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-300 text-sm rounded-lg flex items-center gap-2 animate-shake">
                        <AlertCircle className="w-4 h-4 flex-shrink-0" />
                        {error}
                    </div>
                )}
                
                <form onSubmit={handleCredentialsSubmit} className="space-y-4">
                    {!isLoginMode && (
                        <div className="relative">
                           <UserIcon className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
                           <input 
                                type="text" 
                                placeholder="Имя"
                                required 
                                value={name}
                                onChange={(e) => setName(e.target.value)}
                                className="w-full pl-10 pr-4 py-3 rounded-xl border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-white/5 focus:ring-2 focus:ring-emerald-500 outline-none transition-all"
                            />
                        </div>
                    )}
                    <div className="relative">
                        <Mail className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
                        <input 
                            type="email" 
                            placeholder="Email"
                            required 
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            className="w-full pl-10 pr-4 py-3 rounded-xl border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-white/5 focus:ring-2 focus:ring-emerald-500 outline-none transition-all"
                        />
                    </div>
                    <div className="relative">
                        <Lock className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
                         <input 
                            type="password" 
                            placeholder="Пароль"
                            required 
                            minLength={6}
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                            className="w-full pl-10 pr-4 py-3 rounded-xl border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-white/5 focus:ring-2 focus:ring-emerald-500 outline-none transition-all"
                        />
                    </div>

                    <button 
                        type="submit"
                        disabled={isLoading}
                        className="w-full py-3 mt-4 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-xl shadow-lg shadow-emerald-500/30 transition-all active:scale-95 flex items-center justify-center gap-2 disabled:opacity-70 disabled:cursor-not-allowed"
                    >
                        {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : (
                            <>
                                {isLoginMode ? 'Войти' : 'Продолжить'} <ArrowRight className="w-4 h-4" />
                            </>
                        )}
                    </button>
                </form>

                <div className="mt-6 text-center">
                    <button 
                        type="button"
                        onClick={switchMode}
                        className="text-sm text-gray-500 hover:text-emerald-600 font-medium transition-colors"
                    >
                        {isLoginMode ? "Нет аккаунта? Зарегистрироваться" : "Уже зарегистрированы? Войти"}
                    </button>
                </div>
              </>
            ) : (
              <div className="animate-slide-up">
                 <h2 className="font-serif text-2xl font-bold text-center mb-2 text-gray-900 dark:text-white">
                    Защита от ботов
                </h2>
                <p className="text-center text-gray-500 dark:text-gray-400 mb-8 text-sm">
                  Введите код подтверждения (симуляция): <br/>
                  <span className="font-mono bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded mt-1 inline-block">123456</span>
                </p>
                
                 {error && (
                    <div className="mb-4 p-3 bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-300 text-sm rounded-lg flex items-center gap-2">
                        <AlertCircle className="w-4 h-4 flex-shrink-0" />
                        {error}
                    </div>
                )}

                <form onSubmit={handleRegisterFinalize} className="space-y-6">
                  <div className="relative">
                     <KeyRound className="absolute left-3 top-3 h-5 w-5 text-gray-400" />
                     <input 
                        type="text" 
                        placeholder="Код подтверждения"
                        required 
                        value={verificationCode}
                        onChange={(e) => setVerificationCode(e.target.value)}
                        className="w-full pl-10 pr-4 py-3 rounded-xl border border-gray-300 dark:border-gray-700 bg-gray-50 dark:bg-white/5 focus:ring-2 focus:ring-emerald-500 outline-none text-center tracking-widest font-mono text-lg"
                     />
                  </div>
                  
                  <button 
                        type="submit"
                        disabled={isLoading}
                        className="w-full py-3 bg-emerald-600 hover:bg-emerald-700 text-white font-bold rounded-xl shadow-lg shadow-emerald-500/30 transition-all active:scale-95 flex justify-center"
                    >
                        {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : 'Создать аккаунт'}
                  </button>

                  <button 
                    type="button" 
                    onClick={() => setStep('credentials')}
                    className="w-full text-center text-sm text-gray-500 hover:text-gray-800 dark:hover:text-gray-300"
                  >
                    Назад
                  </button>
                </form>
              </div>
            )}
        </div>
      </div>
    </div>
  );
};

export default AuthModal;